services:
  database:
    build:
      context: .
      dockerfile: database.dockerfile
    networks:
      my-network:
        ipv4_address: 192.168.1.2
    ports:
      - "3307:3306"

  server:
    build:
      context: .
      dockerfile: server.dockerfile
    networks:
      my-network:
        ipv4_address: 192.168.1.3
    ports:
      - "3000:80"
    volumes:
      - ./server:/var/www/html

networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
